"""
AlphaSync Signal Generator — Strategy rule evaluation.

Takes computed indicator values and evaluates them against strategy rules
to produce BUY / SELL / HOLD signals. Used by the Algo Strategy Worker.

Usage:
    from engines.signals import signal_generator, Signal

    signal = signal_generator.evaluate("SMA_CROSSOVER", indicators)
    if signal.action == "BUY":
        # Place order...
"""

import logging
from dataclasses import dataclass
from typing import Optional
from engines.indicators import IndicatorEngine

logger = logging.getLogger(__name__)


@dataclass
class Signal:
    """Trading signal generated by strategy evaluation."""

    action: str  # "BUY", "SELL", "HOLD"
    confidence: float = 0.0  # 0.0 to 1.0
    reason: str = ""
    indicator_values: dict = None

    def __post_init__(self):
        if self.indicator_values is None:
            self.indicator_values = {}


class SignalGenerator:
    """
    Evaluates strategy rules against computed indicators.

    Each strategy type has a dedicated method that examines the latest
    indicator values and returns a Signal. The algo worker calls
    evaluate() with the strategy_type and raw price data — this class
    handles indicator computation + signal logic in one pass.
    """

    def evaluate(
        self,
        strategy_type: str,
        closes: list[float],
        highs: list[float] = None,
        lows: list[float] = None,
        volumes: list[int] = None,
        parameters: dict = None,
    ) -> Signal:
        """
        Main entry point. Computes required indicators and evaluates
        the strategy rules.

        Args:
            strategy_type: One of SMA_CROSSOVER, RSI, MACD, BOLLINGER
            closes: List of closing prices (most recent last)
            parameters: Strategy-specific parameters (periods, thresholds)

        Returns:
            Signal with action, confidence, and reason.
        """
        params = parameters or {}

        match strategy_type:
            case "SMA_CROSSOVER":
                return self._sma_crossover(closes, params)
            case "RSI":
                return self._rsi_strategy(closes, params)
            case "MACD":
                return self._macd_strategy(closes, params)
            case "BOLLINGER":
                return self._bollinger_strategy(closes, params)
            case _:
                logger.warning(f"Unknown strategy type: {strategy_type}")
                return Signal(action="HOLD", reason=f"Unknown strategy: {strategy_type}")

    def _sma_crossover(self, closes: list[float], params: dict) -> Signal:
        """
        SMA Crossover Strategy.

        BUY:  Short SMA crosses above Long SMA (golden cross)
        SELL: Short SMA crosses below Long SMA (death cross)
        """
        short_period = params.get("short_period", 10)
        long_period = params.get("long_period", 20)

        if len(closes) < long_period + 2:
            return Signal(action="HOLD", reason="Insufficient data for SMA crossover")

        short_sma = IndicatorEngine.sma(closes, short_period)
        long_sma = IndicatorEngine.sma(closes, long_period)

        # Need at least 2 valid values for crossover detection
        curr_short, prev_short = short_sma[-1], short_sma[-2]
        curr_long, prev_long = long_sma[-1], long_sma[-2]

        if any(v is None for v in [curr_short, prev_short, curr_long, prev_long]):
            return Signal(action="HOLD", reason="Insufficient indicator data")

        indicator_vals = {
            "short_sma": curr_short,
            "long_sma": curr_long,
            "short_period": short_period,
            "long_period": long_period,
        }

        # Golden cross: short crosses above long
        if prev_short <= prev_long and curr_short > curr_long:
            return Signal(
                action="BUY",
                confidence=0.7,
                reason=f"SMA({short_period}) crossed above SMA({long_period}) — bullish golden cross",
                indicator_values=indicator_vals,
            )

        # Death cross: short crosses below long
        if prev_short >= prev_long and curr_short < curr_long:
            return Signal(
                action="SELL",
                confidence=0.7,
                reason=f"SMA({short_period}) crossed below SMA({long_period}) — bearish death cross",
                indicator_values=indicator_vals,
            )

        return Signal(
            action="HOLD",
            reason="No SMA crossover detected",
            indicator_values=indicator_vals,
        )

    def _rsi_strategy(self, closes: list[float], params: dict) -> Signal:
        """
        RSI Oversold/Overbought Strategy.

        BUY:  RSI crosses above oversold threshold (default 30)
        SELL: RSI crosses above overbought threshold (default 70)
        """
        period = params.get("period", 14)
        oversold = params.get("oversold", 30)
        overbought = params.get("overbought", 70)

        if len(closes) < period + 3:
            return Signal(action="HOLD", reason="Insufficient data for RSI")

        rsi_values = IndicatorEngine.rsi(closes, period)

        curr_rsi = rsi_values[-1]
        prev_rsi = rsi_values[-2]

        if curr_rsi is None or prev_rsi is None:
            return Signal(action="HOLD", reason="Insufficient RSI data")

        indicator_vals = {
            "rsi": curr_rsi,
            "prev_rsi": prev_rsi,
            "period": period,
            "oversold": oversold,
            "overbought": overbought,
        }

        # Buy signal: RSI crosses up from oversold zone
        if prev_rsi <= oversold and curr_rsi > oversold:
            return Signal(
                action="BUY",
                confidence=0.65,
                reason=f"RSI({period}) bounced from oversold ({prev_rsi:.1f} → {curr_rsi:.1f})",
                indicator_values=indicator_vals,
            )

        # Sell signal: RSI crosses into overbought zone
        if prev_rsi < overbought and curr_rsi >= overbought:
            return Signal(
                action="SELL",
                confidence=0.65,
                reason=f"RSI({period}) entered overbought ({prev_rsi:.1f} → {curr_rsi:.1f})",
                indicator_values=indicator_vals,
            )

        return Signal(
            action="HOLD",
            reason=f"RSI at {curr_rsi:.1f} — no signal",
            indicator_values=indicator_vals,
        )

    def _macd_strategy(self, closes: list[float], params: dict) -> Signal:
        """
        MACD Signal Line Crossover Strategy.

        BUY:  MACD line crosses above signal line
        SELL: MACD line crosses below signal line
        """
        fast = params.get("fast_period", 12)
        slow = params.get("slow_period", 26)
        signal_period = params.get("signal_period", 9)

        macd_result = IndicatorEngine.macd(closes, fast, slow, signal_period)
        if macd_result is None:
            return Signal(action="HOLD", reason="Insufficient data for MACD")

        macd_line = macd_result.macd_line
        signal_line = macd_result.signal_line

        curr_macd, prev_macd = macd_line[-1], macd_line[-2]
        curr_signal, prev_signal = signal_line[-1], signal_line[-2]

        if any(v is None for v in [curr_macd, prev_macd, curr_signal, prev_signal]):
            return Signal(action="HOLD", reason="Insufficient MACD data")

        indicator_vals = {
            "macd": curr_macd,
            "signal": curr_signal,
            "histogram": macd_result.histogram[-1],
        }

        # Bullish crossover
        if prev_macd <= prev_signal and curr_macd > curr_signal:
            return Signal(
                action="BUY",
                confidence=0.6,
                reason="MACD crossed above signal line — bullish momentum",
                indicator_values=indicator_vals,
            )

        # Bearish crossover
        if prev_macd >= prev_signal and curr_macd < curr_signal:
            return Signal(
                action="SELL",
                confidence=0.6,
                reason="MACD crossed below signal line — bearish momentum",
                indicator_values=indicator_vals,
            )

        return Signal(
            action="HOLD",
            reason="No MACD crossover",
            indicator_values=indicator_vals,
        )

    def _bollinger_strategy(self, closes: list[float], params: dict) -> Signal:
        """
        Bollinger Bands Mean Reversion Strategy.

        BUY:  Price touches/crosses below lower band (oversold)
        SELL: Price touches/crosses above upper band (overbought)
        """
        period = params.get("period", 20)
        std_dev = params.get("std_dev", 2.0)

        bb_result = IndicatorEngine.bollinger_bands(closes, period, std_dev)
        if bb_result is None:
            return Signal(action="HOLD", reason="Insufficient data for Bollinger Bands")

        curr_price = closes[-1]
        curr_upper = bb_result.upper[-1]
        curr_lower = bb_result.lower[-1]
        curr_middle = bb_result.middle[-1]

        if any(v is None for v in [curr_upper, curr_lower, curr_middle]):
            return Signal(action="HOLD", reason="Insufficient Bollinger data")

        indicator_vals = {
            "price": curr_price,
            "upper": curr_upper,
            "middle": curr_middle,
            "lower": curr_lower,
        }

        # Price at or below lower band → oversold → BUY for mean reversion
        if curr_price <= curr_lower:
            return Signal(
                action="BUY",
                confidence=0.55,
                reason=f"Price (₹{curr_price:.2f}) at lower Bollinger Band (₹{curr_lower:.2f}) — oversold, expecting reversion",
                indicator_values=indicator_vals,
            )

        # Price at or above upper band → overbought → SELL
        if curr_price >= curr_upper:
            return Signal(
                action="SELL",
                confidence=0.55,
                reason=f"Price (₹{curr_price:.2f}) at upper Bollinger Band (₹{curr_upper:.2f}) — overbought",
                indicator_values=indicator_vals,
            )

        return Signal(
            action="HOLD",
            reason=f"Price within bands (₹{curr_lower:.2f} – ₹{curr_upper:.2f})",
            indicator_values=indicator_vals,
        )


# ── Singleton instance ─────────────────────────────────────────────
signal_generator = SignalGenerator()
